//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Logging.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Logging.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace GetCurrentClassLogger() with GetLogger&lt;T&gt;() or GetLogger(typeof(T)) for better peformance.
        /// </summary>
        internal static string Analyzer100Description {
            get {
                return ResourceManager.GetString("Analyzer100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace GetCurrentClassLogger() with GetLogger&lt;T&gt;() or GetLogger(typeof(T)) for better peformance.
        /// </summary>
        internal static string Analyzer100MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace GetCurrentClassLogger() with GetLogger&lt;T&gt;() or GetLogger(typeof(T)) for better peformance.
        /// </summary>
        internal static string Analyzer100Title {
            get {
                return ResourceManager.GetString("Analyzer100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type T in LogManager.GetLogger&lt;T&gt;() call should match the class in which method is called.
        /// </summary>
        internal static string Analyzer101Description {
            get {
                return ResourceManager.GetString("Analyzer101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type T in LogManager.GetLogger&lt;T&gt;() call should match the class in which method is called: {0}.
        /// </summary>
        internal static string Analyzer101MessageFormat {
            get {
                return ResourceManager.GetString("Analyzer101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type T in LogManager.GetLogger&lt;T&gt;() call should match the class in which method is called.
        /// </summary>
        internal static string Analyzer101Title {
            get {
                return ResourceManager.GetString("Analyzer101Title", resourceCulture);
            }
        }
    }
}
